name: Test Form
description: Something Something
title: "[Test Feature] "
body:
  - type: markdown
    attributes:
      value: "Please fill out the form below."
  - type: input
    id: title
    attributes:
      label: Title
      description: "Summary of the request. Maximum 80 characters."
      placeholder: "something something, jfdi"
    validations:
      required: true
      max_length: 80
  - type: textarea
    id: business-justification
    attributes:
      label: Business Justification
      description: "Provide a detailed description of the business justification for this feature. Maximum 200 characters."
      placeholder: "something something, money, risk, etc."
    validations:
      required: true
      max_length: 200
  - type: input
    id: account-name
    attributes:
      label: Account Name
      description: "Enter the account name. Must be in the format of `xxxxx-xxxxx-<env>`."
      placeholder: "somecloud-xtest-dev"
    validations:
      required: true
      pattern: "^[A-Za-z]{5}-.{5}-(dev|stage|prod)$"
      max_length: 5
