name: Test Form
description: Something Something
title: "Account Request - <account-name>"
body:
  - type: markdown
    attributes:
      value: "Please fill out the form below."
  - type: input
    id: description
    attributes:
      label: Description
      description: "Summary of the request. Maximum 80 characters."
      placeholder: "something something, jfdi"
    validations:
      required: true
  - type: textarea
    id: business-justification
    attributes:
      label: Business Justification
      description: "Provide a detailed description of the business justification for this feature. Maximum 200 characters."
      placeholder: "something something, money, risk, etc."
    validations:
      required: false
  - type: input
    id: account-name
    attributes:
      label: Account Name
      description: "Enter the account name. Must be in the format of `xxxxx-xxxxx-<env>`."
      placeholder: "somecloud-xtest-dev"
    validations:
      required: true

  - type: checkboxes
    id: required-access
    attributes:
      label: Required Access
      description: Select the access options below
      options:
        - label: Public Bucket Access
        - label: IGW
        - label: HBA - All
